######################################################################
# Automatically generated by qmake (2.01a) Mon May 2 08:47:04 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gameboard.h sprite.h
SOURCES += gameboard.cpp main.cpp sprite.cpp
