######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 28 23:36:32 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gameboard.h sprite.h
SOURCES += gameboard.cpp main.cpp sprite.cpp
